# Site Settings
title: Hursevich's Resume
url: 'https://alexhurs.github.io/'
baseurl: '' #change it according to your repository name
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: styles
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Alexander Hursevich
tagline: Test Automation Engineer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: "Certified QA Engineer with a technical background and 10 years of IT experience in various areas including functional, integration, UI, regression, and mobile testing.
Have practical experience in developing and maintenance test automation framework including Continuous Integration using best practices."

#sidebar links
email: chursevich@gmail.com
phone: +375 29 6070068
phone1: +995 511194200
skype: aleksander.hursevich
#website: medium.com/@lukaszlenart #do not add http://
linkedin: alexander-hursevich
github: alexhurs
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
# analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
